# This is a basic workflow to help you get started with Actions

name: Test pull requests

# Controls when the workflow will run
on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "pre-merge"
  pre-merge:
    # Name of test
    name: Test and sign
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Runs a single command using the runners shell
      - name: Install prereqs
        run: pip install ansible ansible-lint yamllint molecule molecule-podman podman ansible-sign

      - name: Run molecule test
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
